/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empleado.ec.view;

import com.empleado.ec.bo.EmpleadoBo;
import com.empleado.ec.entity.Empleado;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.ons.Connection;

/**
 *
 * @author Freddie
 */
public class FrmEmpleado extends javax.swing.JFrame {

    private EmpleadoBo ebo = new EmpleadoBo();

    public FrmEmpleado() {
        initComponents();
        try {
            listarEmpleado();
            idMax();
            setTitle("Formulario Empleado");
            setLocationRelativeTo(null);
            setResizable(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void listarEmpleado() throws SQLException {
        ebo.listarEmpleado(tbEmpleado);
    }

    public void idMax(){
        txtIdEmpleado.setText(ebo.getMaxID()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupEstado = new javax.swing.ButtonGroup();
        btnGroupGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdFemenino = new javax.swing.JRadioButton();
        rdMasculino = new javax.swing.JRadioButton();
        rdSoltero = new javax.swing.JRadioButton();
        rdCasado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtIdEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 200, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FORMULARIO EMPLEADO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        txtNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Genero:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cedula:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 200, -1));

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 200, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Estado Civil:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnGroupGenero.add(rdFemenino);
        rdFemenino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdFemenino.setText("Femenino");
        rdFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemeninoActionPerformed(evt);
            }
        });
        jPanel1.add(rdFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        btnGroupGenero.add(rdMasculino);
        rdMasculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rdMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        btnGroupEstado.add(rdSoltero);
        rdSoltero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdSoltero.setText("Soltero");
        rdSoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSolteroActionPerformed(evt);
            }
        });
        jPanel1.add(rdSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnGroupEstado.add(rdCasado);
        rdCasado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdCasado.setText("Casado");
        rdCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCasadoActionPerformed(evt);
            }
        });
        jPanel1.add(rdCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 380, 360));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFemeninoActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasculinoActionPerformed

    private void rdSolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSolteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSolteroActionPerformed

    private void rdCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCasadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtIdEmpleado.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtCedula.getText().isEmpty()
                || txtEdad.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            char estado, genero;
            if (rdCasado.isSelected()) {
                estado = 'C';
            } else {
                estado = 'S';
            }
            if (rdFemenino.isSelected()) {
                genero = 'F';
            } else {
                genero = 'M';
            }
            Empleado emp = new Empleado();
            emp.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            emp.setNombres(txtNombres.getText());
            emp.setApellidos(txtApellidos.getText());
            emp.setCedula(txtCedula.getText());
            emp.setEstadoCivil(estado);
            emp.setGenero(genero);
            emp.setEdad(Integer.parseInt(txtEdad.getText()));
            String mensaje = ebo.agregarEmpleado(emp);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            try {
                listarEmpleado();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtIdEmpleado.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtCedula.getText().isEmpty()
                || txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            char estado, genero;
            if (rdCasado.isSelected()) {
                estado = 'C';
            } else {
                estado = 'S';
            }
            if (rdFemenino.isSelected()) {
                genero = 'F';
            } else {
                genero = 'M';
            }
            Empleado emp = new Empleado();
            emp.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            emp.setNombres(txtNombres.getText());
            emp.setApellidos(txtApellidos.getText());
            emp.setCedula(txtCedula.getText());
            emp.setEstadoCivil(estado);
            emp.setGenero(genero);
            emp.setEdad(Integer.parseInt(txtEdad.getText()));
            String mensaje = ebo.modificarEmpleado(emp);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            try {
                listarEmpleado();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if (txtIdEmpleado.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtCedula.getText().isEmpty()
                || txtEdad.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            char estado, genero;
            if (rdCasado.isSelected()) {
                estado = 'C';
            } else {
                estado = 'S';
            }
            if (rdFemenino.isSelected()) {
                genero = 'F';
            } else {
                genero = 'M';
            }
            String mensaje = ebo.eliminarEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            try {
                listarEmpleado();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tbEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadoMouseClicked
        int selection = tbEmpleado.rowAtPoint(evt.getPoint());
        txtIdEmpleado.setText(tbEmpleado.getValueAt(selection,0)+"");
        txtNombres.setText(tbEmpleado.getValueAt(selection,1)+"");
        txtApellidos.setText(tbEmpleado.getValueAt(selection,2)+"");
        txtCedula.setText(tbEmpleado.getValueAt(selection,3)+"");
        String estado=tbEmpleado.getValueAt(selection, 4)+"";
        if(estado.equals("S")){
            rdSoltero.setSelected(true);
        }else{
            rdCasado.setSelected(true);
        }
        String genero=tbEmpleado.getValueAt(selection, 5)+"";
        if(estado.equals("F")){
            rdFemenino.setSelected(true);
        }else{
            rdMasculino.setSelected(true);
        }
        txtEdad.setText(tbEmpleado.getValueAt(selection,6)+"");
    }//GEN-LAST:event_tbEmpleadoMouseClicked
    public void limpiar() {
        txtIdEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCedula.setText("");
        txtEdad.setText("");
        btnGroupEstado.clearSelection();
        btnGroupGenero.clearSelection();
        idMax();
    }

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGroupEstado;
    private javax.swing.ButtonGroup btnGroupGenero;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdCasado;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JRadioButton rdSoltero;
    private javax.swing.JTable tbEmpleado;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
